---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/nfs/general"
---