---
# handlers file for common

- name: Daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Reboot Server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true
  listen: "Reboot Server"