---
# tasks file for roles/cert-manager
- name: Create cert-manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

- name: Install helm repo for cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Update helm repos
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Install cert-manager via helm
  kubernetes.core.helm:
    state: present
    name:  cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    values:
      installCRDs: true
