---
# tasks file for roles/ingress-nginx
- name: Install helm repo for nginx ingress
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  tags:
  - k3s_setup
  - ingress
  - nginx
  - helm

- name: Update helm repos
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
  tags:
  - k3s_setup
  - ingress
  - nginx
  - helm

- name: Install ingress-nginx via helm
  kubernetes.core.helm:
    state: present
    name:  ingress-nginx
    namespace: kube-system
    chart_ref: ingress-nginx/ingress-nginx
    values:
      defaultBackend.enabled: false   
  tags:
  - k3s_setup
  - ingress
  - nginx
  - helm
