---
- name: Ansible Playbook to Execute Roles on Nodes
  hosts: ztp k3s03 k3s04 k3s05 k3s01 k3s02
  vars:
    # Define any variables here
  roles:
#    - common
    - k3s-server

  tasks:
  # - name: Detect if k3s is already installed
  #   ansible.builtin.systemd:
  #     name: "k3s"
  #   register: k3s_service_status
  #   become: true
  #   ignore_errors: true

  # - debug:
  #     msg: "K3s is installed and enabled on this host"
  #   when: k3s_service_status.status.UnitFileState == "enabled"  