# uninstall.yml
# 
# OOF: not quite idempotent yet, leaves the haproxy install on there still
#      and the certs and file structure, blah blah blah
#      TODO: Fix the lack of idempotency
---
- name: Uninstall k3s on servers
  hosts: servers
  vars:
    # Define any variables here
  roles:
    #- nothign
  tasks:
    - name: Uninstall k3s on servers
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true

- name: Uninstall k3s on agents
  hosts: agents
  vars:
    # Define zee variables herez
  roles:
    # nothign
  tasks: 
    - name: Uninstall k3s on agents
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
